export const LEEPA_PARCELS_LAYER =
  "https://services2.arcgis.com/LvWGAAhHwbCJ2GMP/arcgis/rest/services/Lee_County_Parcels/FeatureServer/0";

export const LEEPA_SOURCE_SYSTEM = "leepa";

export const LEEPA_OBJECT_ID_FIELD = "OBJECTID";

export type LeepaParcelAttributes = {
  OBJECTID: number;
  STRAP: string | null;
  FOLIOID: number | null;
  TRSPARCEL: string | null;
  DORCODE: string | null;
  CONDOTYPE: string | null;
  NUMUNITS: number | null;
  GISACRES: number | null;
  FRONTAGE: number | null;
  DEPTH: number | null;
  ZONING: string | null;
  ZONINGAREA: string | null;
  LANDUSECOD: number | null;
  LANDUSEDES: string | null;
  SITEADDR: string | null;
  SITENUMBER: string | null;
  SITESTREET: string | null;
  SITEUNIT: string | null;
  SITECITY: string | null;
  SITEZIP: string | null;
  JUST: number | null;
  ASSESSED: number | null;
  TAXABLE: number | null;
  LAND: number | null;
  BUILDING: number | null;
  LXFV: number | null;
  BXFV: number | null;
  NEWBUILT: number | null;
  AGAMOUNT: number | null;
  HSTDAMOUNT: number | null;
  SNRAMOUNT: number | null;
  WHLYAMOUNT: number | null;
  WIDAMOUNT: number | null;
  WIDRAMOUNT: number | null;
  DISAMOUNT: number | null;
  HISTAMOUNT: number | null;
  BLDGCOUNT: number | null;
  MINBUILTY: number | null;
  MAXBUILTY: number | null;
  TOTALAREA: number | null;
  HEATEDAREA: number | null;
  MAXSTORIES: number | null;
  BEDROOMS: number | null;
  BATHROOMS: number | null;
  GARAGE: string | null;
  CARPORT: string | null;
  POOL: string | null;
  BOATDOCK: string | null;
  SEAWALL: string | null;
  O_NAME: string | null;
  O_OTHERS: string | null;
  O_CAREOF: string | null;
  O_ADDR1: string | null;
  O_ADDR2: string | null;
  O_CITY: string | null;
  O_STATE: string | null;
  O_ZIP: string | null;
  O_COUNTRY: string | null;
  S_1DATE: number | null;
  S_1AMOUNT: number | null;
  S_1VI: string | null;
  S_1TC: string | null;
  S_1OR_NUM: string | null;
  S_2DATE: number | null;
  S_2AMOUNT: number | null;
  S_2VI: string | null;
  S_2TC: string | null;
  S_2OR_NUM: string | null;
  S_3DATE: number | null;
  S_3AMOUNT: number | null;
  S_3VI: string | null;
  S_3TC: string | null;
  S_3OR_NUM: string | null;
  S_4DATE: number | null;
  S_4AMOUNT: number | null;
  S_4VI: string | null;
  S_4TC: string | null;
  S_4OR_NUM: string | null;
  LEGAL: string | null;
  MUNICODE: string | null;
  CREATEYEAR: number | null;
  Property_URL: string | null;
  LATITUDE: number | null;
  LONGITUDE: number | null;
  STATEDAREA: string | null;
  STATEDAREA_SQFT: number | null;
};

export type LeepaFeature = { attributes: LeepaParcelAttributes };
